atlas_org_id = "<Insert your Atlas Org ID>"
atlas_project_name = "myFirstProject"
environment = "dev"
cluster_instance_size_name = "M10"
cloud_provider = "AZURE"
atlas_region = "US_EAST_2"
mongodb_version = "7.0"
ip_address = "<Insert your IP Address>"
